version: "3.7"

services:
  app:
    build: ./
    restart: always
    env_file: ./.env
    container_name: kiness_admin
    image: kiness_admin
    ports:
      - "7840:80"
    environment:
      - VITE_BASE_URL=$VITE_BASE_URL
